### PR TITLE
Burton concurrent destination gc

### PR DESCRIPTION
**Pull request by burtonator**
Improves performance of concurrent destination GC dramatically.

### CODE REVIEW

**Comment by tbain98** [comment]
Some of your changes appear to be conflicts between your Eclipse autoformatting schema and the conventions in use in the ActiveMQ code (in particular, you appear to be adding spaces around arguments in method calls, which isn't the convention in the rest of the codebase).  Can you please clean that up?  I think this is a good feature that should be merged (and I'll lobby Gary/Tim/whoever to do the merge, since it's sat untouched for a while), but I can't advocate merging something that takes code that is formatted according to the project conventions and makes format-only changes to move away from those conventions (especially since those changes make the commit look more complicated than it really is).

**Comment by burtonator** [comment]
Ah.  No problem. I hadn't even realized I did that.  And I agree that it's bad form to reformat existing code. I'll diff to the original and also verify that my code is compliant.

**Comment by tbain98** [comment]
Are you still planning to clean up this PR and try to get it merged?  Or are you going to withdraw it and request a merge into 5.12.x?  (That's probably the better option, since I don't expect this will get backported to 5.11...)

**Comment by burtonator** [comment]
Probably going to get it to merge into 5.12… I’ve since done more work to
it to fix some other related bugs.

It’s taking me longer because a bug was introduced somewhere in 5.11 which
introduces problems with advisory queues and the memory store.  So I can’t
port my code to 5.11/5.12.

Fortunately, my changes are pretty straight forward and would be easy to
port to 5.12 I think.



On Sat, May 30, 2015 at 5:34 PM, Tim Bain <notifications@github.com> wrote:

> Are you still planning to clean up this PR and try to get it merged? Or
> are you going to withdraw it and request a merge into 5.12.x? (That's
> probably the better option, since I don't expect this will get backported
> to 5.11...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/activemq/pull/65#issuecomment-107103394>.
>



-- 

Founder/CEO Spinn3r.com
Location: *San Francisco, CA*
blog: http://burtonator.wordpress.com
… or check out my Google+ profile
<https://plus.google.com/102718274791889610666/posts>

**Comment by lucastetreault** [comment]
Can one of the admins verify this patch?

**Comment by cshannon** [comment]
Closing old PRs without any recent activity. If something is still relevant it can be re-opened.

**Pull request closed without merging**
