### PR TITLE
[AMQ-8274] Allow url parameters to specify initial sort order

### PR DESCRIPTION
**Pull request by maxfortun**
This change will allow to pass `sortColumnId` and `sortOrder` url parameters to console's queues view, thus ordering the data on-load. This is very useful when visually monitoring dequeued messages change over time.

### CODE REVIEW

**Comment by mattrpav** [comment]
Hello @maxfortun, thanks for the PR. Will review. Do you happen to have a JIRA to reference for this? 

If not, it is quick to open one at [Apache JIRA](https://issues.apache.org/jira) -- select 'ActiveMQ' as the project and 'Web Console' as the component. Release notes are generated from the JIRAs, so features and fixes like this can be communicated to users.

Thanks!

**Comment by maxfortun** [comment]
Thank you, just created the issue:

https://issues.apache.org/jira/browse/AMQ-8274

**Comment by maxfortun** [comment]
https://issues.apache.org/jira/browse/AMQ-8274

**Comment by maxfortun** [comment]
I am not sure why maven tests are failing. My changes were only to a front end javascript file. Is this a blocker for a merge?

**Comment by mattrpav** [comment]
@maxfortun The tests probably failing due to previous Jenkins build rules. If you rebase the PR, it should be able to go green.

**Comment by maxfortun** [comment]
How do I get this PR merged in?

**Comment by mattrpav** [comment]
I’m working on tasks to get into 5.16.4. This is one. Should be within the next week. Thanks!

**Comment by maxfortun** [comment]
Would this be merged into 5.17 as well?

**Comment by jbonofre** [comment]
I will yes.

**Pull request closed without merging**
