### PR TITLE
[AMQ-8515] FailoverTransport should handle MaxFrameSizeExceededException

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by mattrpav** [comment]
@cshannon please give this a look over, it'd be good to get it into 5.17.0. This fix addresses the use case that originally sparked the improvement-- failover with a message that server-side maxFrameSize check failing results in infinite retries.

**Comment by cshannon** [comment]
@mattrpav - Nice catch, this is definitely an issue with the exception type and this seems like the right fix. Thanks for updating the tests, they look good. We definitely don't want to be attempting to reconnect on this failure as it would never work so it needs to be propagated back up.

**Review by cshannon — APPROVED** [review]

**Comment by cshannon** [comment]
As long as the CI tests pass I think this is good to merge

**Comment by mattrpav** [comment]
First round of tests passed clean. I pushed an update of change that included comments in the test w/ link to the jira about how client check=false + failover + server check=true is an infinite retry.

I'll merge once the next round of tests goes green.

Thanks!

**Pull request merged**
