### PR TITLE
upgrade jaxb-basics-version to 0.12.0

### PR DESCRIPTION
**Pull request by ehossack-aws**
A dependency bot recommended bumping this version. No breaking changes.
I see no reason why not :)

### CODE REVIEW

**Comment by mattrpav** [comment]
This requires the JDK 9+ target-version.  This dep is why I created #712

**Comment by mattrpav** [comment]
Yep, I might have overstated jaxb2-basics went to 9+ for build. This also requires jaxb-2.3.x api's and impl jars. I believe the fix is more than just update this module. Some of the downstream modules may need 9+. 

What did you test?

**Comment by jbonofre** [comment]
FYI, jaxb-basics is used in the Karaf features and the runtime config. Did you test these parts ? For Karaf, it should not be a problem.

**Review by jbonofre — APPROVED** [review]
I tested in Karaf and thanks to the dependency flag, jaxb basics capabilities are already provided by Karaf. I also tested the runtimeConfigurationPlugin (which uses jaxb basics) and it works fine.

**Pull request merged**
