### PR TITLE
improve Reproducible Builds

### PR DESCRIPTION
**Pull request by hboutemy**
this won't fix every issue, but improve the situation
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/activemq/README.md

### CODE REVIEW

**Comment by hboutemy** [comment]
in the reproducible-central page,  there are link to diffoscope results that show the different problems found, for example https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/activemq/activemq-parent-5.17.0.diffoscope

**Comment by hboutemy** [comment]
to me, once this PR is merged, the only non-reproducible bits are a stupid timestamp, I'll need to chase in Spring later
```
├── META-INF/spring.handlers
│ @@ -1,3 +1,3 @@
│  #Generated by xbean-spring
│ -#Thu May 05 08:24:00 CEST 2022
│ +#Thu May 05 08:25:21 CEST 2022
```

**Comment by mattrpav** [comment]
> to me, once this PR is merged, the only non-reproducible bits are a stupid timestamp, I'll need to chase in Spring later
> 
> ```
> ├── META-INF/spring.handlers
> │ @@ -1,3 +1,3 @@
> │  #Generated by xbean-spring
> │ -#Thu May 05 08:24:00 CEST 2022
> │ +#Thu May 05 08:25:21 CEST 2022
> ```

FYI00 You might need to run this one down via xbean project, and not spring.

**Comment by mattrpav** [comment]
@hboutemy would you please rebase against main and squash your commits? I'd think this would be good to get going in 5.18.x

**Comment by hboutemy** [comment]
> FYI00 You might need to run this one down via xbean project, and not spring.

yes, https://issues.apache.org/jira/browse/XBEAN-335 created

**Comment by hboutemy** [comment]
> @hboutemy would you please rebase against main and squash your commits? I'd think this would be good to get going in 5.18.x

@mattrpav done, with workarounds for plugins injecting timestamps: we're near full Reproducible Builds for 5.18.0

**Comment by hboutemy** [comment]
@mattrpav PR rebased

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
