### PR TITLE
[AMQ-8248] Upgrade Jetty to 9.4.40.v20210413

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by mattrpav** [comment]
Created PR to kick off test suite against updated Jetty

**Comment by jbonofre** [comment]
I had the PR ready already ;)

**Comment by mattrpav** [comment]
No prob. You can cancel mine. I was just wanting to kick off the Jenkins to verify

**Comment by jbonofre** [comment]
@mattrpav no it's fine, it's basically the same ;)

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
