### PR TITLE
Keep track of free pages during Pagefile checkpoints

### PR DESCRIPTION
**Pull request by alanprot**

### CODE REVIEW

**Comment by jbonofre** [comment]
I fixed the conflict locally, I'm testing and I will merge manually. Thanks.

**Comment by cshannon** [comment]
@jbonofre - I am minus -1 on the merge for now as I am not sure if there is a consensus.  @gtully was looking at this quite a bit when it was being worked on so I would prefer to have his input before merging this.

**Comment by jbonofre** [comment]
@cshannon fair enough. Let's postpone to get a consensus. I just want to give feedback to contributors providing PRs.

**Comment by lucastetreault** [comment]
Can one of the admins verify this patch?

**Comment by jbonofre** [comment]
Auto closed

**Pull request closed without merging**
