### PR TITLE
[AMQ-7249] Upgrade to Jetty 9.4.19.v20190610

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by coheigea** [comment]
@jbonofre I have a fix for the failing tests in the http module. The karaf itests are also failing though.

**Comment by coheigea** [comment]
@jbonofre The karaf itests are failing with:

Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve activemq-broker/5.16.0.SNAPSHOT: missing requirement [activemq-broker/5.16.0.SNAPSHOT] osgi.identity; osgi.identity=activemq; type=karaf.feature; version="[5.16.0.SNAPSHOT,5.16.0.SNAPSHOT]" [caused by: Unable to resolve activemq/5.16.0.SNAPSHOT: missing requirement [activemq/5.16.0.SNAPSHOT] osgi.identity; osgi.identity=activemq-karaf; type=osgi.bundle; version="[5.16.0.SNAPSHOT,5.16.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve activemq-karaf/5.16.0.SNAPSHOT: missing requirement [activemq-karaf/5.16.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.apache.activemq.console.command)" [caused by: Unable to resolve org.apache.activemq.activemq-osgi/5.16.0.SNAPSHOT: missing requirement [org.apache.activemq.activemq-osgi/5.16.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.transaction)(version>=1.3.0)(!(version>=2.0.0)))"]]]

**Comment by jbonofre** [comment]
@coheigea I think I already have a fix. I gonna rebase, squash and push.

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
