### PR TITLE
ActiveMQ Logo

### PR DESCRIPTION
**Pull request by milapbhojak**
Hi Community,

Milap here, Product designer from India. I have designed few options for ActiveMQ logo. I have referred Apache Foundation style guide. Please let me know your feedback. :)

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I really liked your contribution.. but your PR here is broken...

You should have done a PR from your rebased master. towards the new master..it should include just one commit.


I couldn't even find a commit here that includes your change. I think you are referring the file from somewhere else?

**Comment by milapbhojak** [comment]
@clebertsuconic Let me create a new pull request.

**Comment by gemmellr** [comment]
Now that you created #253 it would be good to close this PR out.

**Comment by niwa-sama** [comment]
Why is org.apache.activemq.selector package empty?

**Comment by tabish121** [comment]
@niwa-sama That's a question for the ActiveMQ users mailing list

**Pull request closed without merging**
