### PR TITLE
AMQ-7442 - Adding build support for JDK 11

### PR DESCRIPTION
**Pull request by cshannon**
This is the initial work to allow the broker to be compiled and build
with JDK 11 while keeping the source/target Java version at 8 so it
will also run on JDK 8+

### CODE REVIEW

**Comment by cshannon** [comment]
closing for now as we need to drop Scala and LevelDB

**Comment by jbonofre** [comment]
I also have a branch with full build on JDK 11+, I will open and will let you know.

**Comment by lucastetreault** [comment]
Can one of the admins verify this patch?

**Comment by jbonofre** [comment]
Superseded by #647

**Pull request closed without merging**
