### PR TITLE
[AMQ-8284] Update jetty to 9.4.41.v20210516

### PR DESCRIPTION
**Pull request by mattrpav**
- Confirm update w/ deprecation fixes

### CODE REVIEW

**Review by jbonofre — CHANGES_REQUESTED** [review]
Can you please amend your commit with the right Jira number ? It's AMQ-8284.

**Review by jbonofre — APPROVED** [review]

**Comment by jbonofre** [comment]
For the record, you can rebase and squash, and then force push to have a single commit instead of two.

**Comment by mattrpav** [comment]
Will do.  Was looking into Jetty 10 and Jettty 11 for a hot minute-- but we'd need a JDK v11 min required

**Comment by jbonofre** [comment]
It's too early to upgrade to jetty 10 or jetty 11 as it will break the third party (Karaf), and also API change. I would target this once Pax Web/Karaf will support it.

**Pull request merged**
