### PR TITLE
[AMQ-6160] fix NPE; use messageId.getFutureOrSequenceLong() as sequen…

### PR DESCRIPTION
**Pull request by jenshadlich**
…ceId if entryLocator is NULL

### CODE REVIEW

**Comment by davsclaus** [comment]
@gtully @tabish121 does this PR look okay to you guys? I am not familiar with that future thingy

**Comment by tabish121** [comment]
There doesn't appear to be any tests here to validate that this is still an issue, many fixes have gone into the codebase since this was opened.

**Comment by lucastetreault** [comment]
Can one of the admins verify this patch?

**Comment by jbonofre** [comment]
I'm not able to reproduce it. I think it has been already resolved as `entryLocator` doesn't seem to be null.

**Pull request closed without merging**
