### PR TITLE
Add ACTIVEMQ_WEB_USER to groups.properties file in docker

### PR DESCRIPTION
**Pull request by Bizman345**
Couldn't get access in web console when use ACTIVEMQ_WEB_USER  environment variable for docker. Console threw "HTTP ERROR 403 !role"

### CODE REVIEW

**Comment by kenliao94** [comment]
Did you mean to merge it to `main` branch instead of 1apache:activemq-6.1.x` branch? Why is the fix 6.1.x specific?

**Comment by Bizman345** [comment]
> Did you mean to merge it to `main` branch instead of 1apache:activemq-6.1.x` branch? Why is the fix 6.1.x specific?

Hello.
Yes. I meant merge it to main.
As I understand, I need to close this PR and create new one for `main` branch(this branch was created from apache:activemq-6.1.x). Am I right?

**Comment by kenliao94** [comment]
> Hello.
> Yes. I meant merge it to main.
> As I understand, I need to close this PR and create new one for main branch(this branch was created from > apache:activemq-6.1.x). Am I right?

Correct. Thanks!

**Comment by Bizman345** [comment]
> Couldn't get access in web console when use ACTIVEMQ_WEB_USER environment variable for docker. Console threw "HTTP ERROR 403 !role"

Close this PR.
The new one - https://github.com/apache/activemq/pull/1279

**Comment by Bizman345** [comment]
Close this PR.
The new one - https://github.com/apache/activemq/pull/1279

**Pull request closed without merging**
