### PR TITLE
[AMQ-9434] broker Linux script improvement

### PR DESCRIPTION
**Pull request by cliviu**
allow starting ActiveMQ on Linux when there is space in the folder path

### CODE REVIEW

**Comment by cliviu** [comment]
https://issues.apache.org/jira/browse/AMQ-9434

**Comment by jbonofre** [comment]
As you based your change on `activemq-5.17.x` branch, I will create another PR for `main`.

**Comment by jbonofre** [comment]
Superseded by #1162

**Comment by cliviu** [comment]
will the change be merged on the activemq-5.17.x branch also?

**Comment by jbonofre** [comment]
yes, I always backport/cherry pick to active bramches (adapting when needed).

**Pull request closed without merging**
