### PR TITLE
AMQ-6506: Increase OSGi version range for package import javax.jms

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by davsclaus** [comment]
ActiveMQ dont support JMS 2.0 yet so not sure if its good to increase that osgi range

**Comment by graben** [comment]
Well, the same patch has already been done on activemq-osgi bundle. (AMQ-5574)

**Comment by davsclaus** [comment]
Ah okay lets make them the same.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
