### PR TITLE
AMQ-7450 - Put some restrictions on the URLs that are allowed in Blob…

### PR DESCRIPTION
**Pull request by coheigea**
…Messages

The idea is for the default + FTP blob download strategies, to check that the protocol, host + port match the configured upload URL of the BlobTransferPolicy.

### CODE REVIEW

**Comment by jbonofre** [comment]
Weird, it seems to pass on my machine.

**Comment by jbonofre** [comment]
I'm doing a full build on my machine to be sure.

**Comment by jbonofre** [comment]
I'm able to reproduce the failure:
186 [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.19 s <<< FAILURE! - in org.apache.activemq.blob.DownloadStrategyTest
187 [ERROR] testFTPBlobDownloadStrategy(org.apache.activemq.blob.DownloadStrategyTest)  Time elapsed: 0.08 s  <<< ERROR!
188 org.apache.commons.net.MalformedServerReplyException:
189 Could not parse response code.
190 Server Reply: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
191   at org.apache.activemq.blob.DownloadStrategyTest.testFTPBlobDownloadStrategy(DownloadStrategyTest.java:113)
192

**Comment by jbonofre** [comment]
OK, I confirm that `master` works but not `pr-517`.

**Comment by coheigea** [comment]
@jbonofre I just pushed a fix.

**Pull request merged**
