### PR TITLE
AMQ-6327 - Remove System.out.println

### PR DESCRIPTION
**Pull request by snurmine**
Accidently added System.out.println in https://github.com/apache/activemq/pull/267

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Wouldn’t be better to replace by a log.debig or Info instead ?

**Comment by snurmine** [comment]
It left there accidently. If logging will be added, then it could be using proper logger

**Comment by yinian** [comment]
I want ask a question? how to run the test case in activemq-leveldb-store.
Or can you tell me how to run it. Thank you

**Comment by snurmine** [comment]
I am not familiar with this project that much, but tried with
mvn -Dtest=IndexRebuildTest test 
and it ran single test case. It seems to be maven project so instruction in http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html might work.

**Comment by hzbarcea** [comment]
I have an idea who didn't do a proper review of #267. Many thanks for pointing it out! I'll take care of it tomorrow if somebody doesn't beat me to it.

**Pull request closed without merging**
