### PR TITLE
Add Jenkinsfile for s390x

### PR DESCRIPTION
**Pull request by srajmane**
Add Jenkinsfile for s390x

https://issues.apache.org/jira/browse/AMQ-8133

### CODE REVIEW

**Comment by srajmane** [comment]
@mattrpav @jbonofre 
Could you please setup/create a job for s390x ? I have created jenkinsfile for s390x in this PR.

**Comment by mattrpav** [comment]
@srajmane do you have any stats of build times on s390x? on the x86 stuff the build can run for several hours.

I'm thinking step 1 re s390x may be to have weekly schedule vs build on-every-PR

**Comment by srajmane** [comment]
@mattrpav Build time is 6-6.5 Hrs on s390x. For now, it is okay to have weekly schedule.

**Comment by srajmane** [comment]
@mattrpav Could you please have a look?  Thanks !!

**Comment by jbonofre** [comment]
I guess it won't work on Apache Jenkins right ? Is it for a fork you have on your side ?

**Comment by mattrpav** [comment]
@jbonofre the Jenkins error is on the buggy test that fails on other CI runs as well.

@srajmane is there a way to merge the change so we have one JenkinsFile? That way we would inherit pipeline changes without having to keep two files in sync (things like JDK LTS runs, mvn verify, etc)

**Comment by srajmane** [comment]
@mattrpav Thank you for the update. Sure, I will check and will try to keep one Jenkinsfile.

**Comment by jbonofre** [comment]
My point is that we don't have all executors available on Apache Jenkins.

**Comment by mattrpav** [comment]
> My point is that we don't have all executors available on Apache Jenkins.

Apache Infra added a couple for s390

**Comment by jbonofre** [comment]
> > My point is that we don't have all executors available on Apache Jenkins.
> 
> Apache Infra added a couple for s390

OK, last time I asked it was in discussion because it's hard to manage. Fair enough then ;)

**Comment by srajmane** [comment]
@jbonofre @mattrpav Added s390x node in Jenkinsfile. Please have a look. 
Thanks !!

**Comment by srajmane** [comment]
@jbonofre @mattrpav 
 Could you please have a look? Thanks !!

**Comment by mattrpav** [comment]
@srajmane I opened #956 which uses parameters (manual execution) as a first step. Need to understand how long the build runs on Apache's s390x. If we get quick turn-around times, we can add it to all PRs moving forward.

**Pull request closed without merging**
