### PR TITLE
[AMQ-7340] Improve scheduled message performance

### PR DESCRIPTION
**Pull request by lucastetreault**
We recently encountered a similar performance degradation as is described here: https://issues.apache.org/jira/browse/AMQ-7340 

A specific example we encountered was with around 20k messages scheduled very quickly where each message adds 100ms delay times with the previous message.
Example:
message 1 > delay time 100ms
message 2 > delay time 200ms
message 3 > delay time 300ms
...
message 10,000 >> delay time 1000000ms (1000s)
...
message 20,000 >> delay time 2000000ms (2000s)

If delivered on schedule all these messages should be moved to the queue within ~33 minutes but we observed that it took nearly 3 hours for all the messages to be moved to the queue. 

After diving deep on the issue it seems the main loop that processes scheduled messages process them by traversing the B+ Tree index from the root to find the leftmost leaf node which contains the scheduled jobs with the earliest executionTime. This traversal does a disk read at each branch and unmarshals the raw data before moving to the next branch and is not cached for future reads as far as I can tell. The scheduled jobs in that leaf are processed then we repeat the traversal to find the execution time of the next batch of jobs to calculate how long the loop should sleep for. So for every loop, we find the left most node twice, at the start and end of the loop. It seems like this loop can take a long time and we end up falling behind and not being able to catch up since we're processing one node at a time. 

This change still does the traversal from the root node to the leftmost node at the start of the loop but once it finds that leftmost node it will iterate over the leaf nodes sequentially until it finds a job with an execution time greater than the current time. This means that it will always "catch up" on every iteration of the loop. The index is locked for the duration of the iteration so there's probably some risk that scheduled messages can't make it in but in practice it doesn't seem like an issue. I ran 100 connections against a broker scheduling messages as fast as they could with 100ms delays as in the example above and I was able to schedule 120k messages within a couple of seconds without any issues.

### CODE REVIEW

**Comment by jbonofre** [comment]
I'm doing a new pass/test on this one.

**Review by jbonofre — APPROVED** [review]

**Comment by lucastetreault** [comment]
Thanks JB!

**Comment by lovemai073** [comment]
Hi

I would like to know if this issue has been published on a specific version? or not yet published?
I tested on version 5.16.4 and it doesn't seem to be fixed.

Thank you.

**Comment by jbonofre** [comment]
@lovemai073 it has been fixed on 5.17.0 but not backported on 5.16.4. I can include on 5.16.5 if needed.

**Comment by lovemai073** [comment]
Hi @jbonofre
No problem, just follow your schedule is ok.
I just confirm if this issue was published.

Thanks.

**Comment by jbonofre** [comment]
@lovemai073 I just double checked and actually, the change is included on 5.16.x:

```
commit fc7a68a8bcf24492d3b2fe5426d366103b3e0e8f
Author: Lucas Tétreault <tetlucas@amazon.com>
Date:   Wed Nov 24 01:06:47 2021 -0800

    Use B+ Tree iterator instead of DFS to find scheduled jobs to be executed
    
    (cherry picked from commit 60859b0b7fa93b001ca2b0ac2f2385386cb2f47d)

```

So, it's included in ActiveMQ 5.16.4.

**Comment by jbonofre** [comment]
I'm not the author of the change, neither the reviewer. So let me take a look about the change.

**Comment by mattrpav** [comment]
@lovemai073 what message volume are you using to test? Ie number of messages and average size?  

For that given volume, how long does it take on your system?

**Comment by lovemai073** [comment]
My test scenario is the same as mentioned by @lucastetreault.
- MQ version: Broker engine version 5.16.4
- Broker instance type: [mq.m5.large](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/broker-instance-types.html#activemq-broker-instance-types)(vCPU:8 memory:8G) host on AWS MQ service.
- Test case: Test 500ms and 1000ms delayed messages in the 2 different MQ.
- send message volume is 100,000
-message size is a string of consecutive numbers (ex: 000000~099999)

#### 1. 500ms：
Using 100,000 messages, each message delay is accumulated to 500ms. In this case, the consumer can consume the message in about 500~800ms.

#### [The 30,000th time spent]
----------
[2022-05-25 11:46:46.574] 1 -- INFO  -- contents NmsTextMessage { 030001 }.
[2022-05-25 11:46:47.074] 1 -- INFO  -- contents NmsTextMessage { 030002 }.
[2022-05-25 11:46:47.569] 1 -- INFO  -- contents NmsTextMessage { 030003 }.
[2022-05-25 11:46:48.069] 1 -- INFO  -- contents NmsTextMessage { 030004 }.
[2022-05-25 11:46:48.579] 1 -- INFO  -- contents NmsTextMessage { 030005 }.
[2022-05-25 11:46:49.063] 1 -- INFO  -- contents NmsTextMessage { 030006 }.
[2022-05-25 11:46:49.574] 1 -- INFO  -- contents NmsTextMessage { 030007 }.

#### [The 70,000th time spent]
----------
[2022-05-25 17:29:04.582] 1 -- INFO  -- contents NmsTextMessage { 070001 }.
[2022-05-25 17:29:05.082] 1 -- INFO  -- contents NmsTextMessage { 070002 }.
[2022-05-25 17:29:05.582] 1 -- INFO  -- contents NmsTextMessage { 070003 }.
[2022-05-25 17:29:06.082] 1 -- INFO  -- contents NmsTextMessage { 070004 }.
[2022-05-25 17:29:06.582] 1 -- INFO  -- contents NmsTextMessage { 070005 }.
[2022-05-25 17:29:07.082] 1 -- INFO  -- contents NmsTextMessage { 070006 }.
[2022-05-25 17:29:07.583] 1 -- INFO  -- contents NmsTextMessage { 070007 }.

#### [The 100,000th time spent]
----------
[2022-05-25 21:46:04.591] 1 -- INFO  -- contents NmsTextMessage { 099993 }.
[2022-05-25 21:46:05.092] 1 -- INFO  -- contents NmsTextMessage { 099994 }.
[2022-05-25 21:46:05.592] 1 -- INFO  -- contents NmsTextMessage { 099995 }.
[2022-05-25 21:46:06.092] 1 -- INFO  -- contents NmsTextMessage { 099996 }.
[2022-05-25 21:46:07.093] 1 -- INFO  -- contents NmsTextMessage { 099997 }.
[2022-05-25 21:46:07.593] 1 -- INFO  -- contents NmsTextMessage { 099998 }.
[2022-05-25 21:46:08.093] 1 -- INFO  -- contents NmsTextMessage { 099999 }.

The estimated time for the message to be consumed
----------
((100000*500)/1000) / 60 = 833.33mins
833.33 / 60 = 13.88 H

Actual consumption time
----------
StartTime: 2022-05-25 07:33:43.826 UTC+0
EndTime: 2022-05-25 21:46:08.093 UTC+0
Total: 14H, 12min, 24s (Can notice a little delay)


#### 2. 1000ms：

#### [The 30,000th time spent]
----------
[2022-05-25 18:11:58.025] 1 -- INFO  -- contents NmsTextMessage { 030000 }.
[2022-05-25 18:11:59.025] 1 -- INFO  -- contents NmsTextMessage { 030001 }.
[2022-05-25 18:12:00.025] 1 -- INFO  -- contents NmsTextMessage { 030002 }.
[2022-05-25 18:12:01.025] 1 -- INFO  -- contents NmsTextMessage { 030003 }.
[2022-05-25 18:12:02.025] 1 -- INFO  -- contents NmsTextMessage { 030004 }.
[2022-05-25 18:12:03.025] 1 -- INFO  -- contents NmsTextMessage { 030005 }.
[2022-05-25 18:12:04.025] 1 -- INFO  -- contents NmsTextMessage { 030006 }.

#### [The 70,000th time spent]
----------
[2022-05-26 05:28:14.518] 1 -- INFO  -- contents NmsTextMessage { 070000 }.
[2022-05-26 05:28:15.514] 1 -- INFO  -- contents NmsTextMessage { 070001 }.
[2022-05-26 05:28:16.517] 1 -- INFO  -- contents NmsTextMessage { 070002 }.
[2022-05-26 05:28:17.517] 1 -- INFO  -- contents NmsTextMessage { 070003 }.
[2022-05-26 05:28:18.517] 1 -- INFO  -- contents NmsTextMessage { 070004 }.
[2022-05-26 05:28:19.517] 1 -- INFO  -- contents NmsTextMessage { 070005 }.
[2022-05-26 05:28:20.517] 1 -- INFO  -- contents NmsTextMessage { 070006 }.

#### [The 86,000th time spent]

Since I set the expired period of the message to 1 day, it will reach the 24h limit when it reaches 86398, and the following messages will be put into the DLQ
----------
[2022-05-26 10:05:26.015] 1 -- INFO  -- contents NmsTextMessage { 086393 }.
[2022-05-26 10:05:27.015] 1 -- INFO  -- contents NmsTextMessage { 086394 }.
[2022-05-26 10:05:28.015] 1 -- INFO  -- contents NmsTextMessage { 086395 }.
[2022-05-26 10:05:29.015] 1 -- INFO  -- contents NmsTextMessage { 086396 }.
[2022-05-26 10:05:30.015] 1 -- INFO  -- contents NmsTextMessage { 086397 }.
[2022-05-26 10:05:31.015] 1 -- INFO  -- contents NmsTextMessage { 086398 }.

The estimated time for the message to be consumed
----------
((86398*1000)/1000) / 60 = 1439.97mins
1439.97 / 60 = 23.999 H

Actual consumption time
----------
StartTime: 2022-05-25 09:44:37.678
EndTime: 2022-05-26 10:05:31.015
Total: 24H, 20min

The time to get the last 86398 message on the consumer side is already limit to 24H.
Later, it has directly into DLQ because it exceeds the message TimeToLive for 1 day(24H), it means that there are about 10,000+ messages, need takes more time to been consumed.

**Comment by lovemai073** [comment]
Hi @lucastetreault,
Thanks for the tip, I noticed that I was missing a main test case.
I did the following test again with the new MQ environment.

- MQ version: Broker engine version 5.16.4
- Broker instance type: mq.m5.large(vCPU:8 memory:8G) with EBS host on AWS MQ service.
- Test case: Test 100ms delayed messages. This is the main issue in the previous version.
- send message volume is 100,000 via 1 producer
- message size is a string of consecutive numbers (ex: 000000~099999)
- consumer: Use 4 consumers, I noticed that delay time is 100ms, which means that the consumer must get 10+ messages in 1 second.

#### Test-1. 100ms with 4 consumer.

The expected time for the message to be consumed

>((100000*100)/1000) / 60 = 166.67mins
166.67 / 60 = 2.7H

Actual consumption time

>StartTime: 2022-06-02 14:50:13.276
EndTime:2022-06-02 17:37:39.99
Total: 2H 48Mins => 168 mins


#### Test-2. 100ms with 4 consumer.
The expected time for the message to be consumed
>((100000*100)/1000) / 60 = 166.67mins
166.67 / 60 = 2.7H

Actual consumption time
>StartTime: 2022-06-03 04:04:45.827
EndTime:2022-06-03 06:53:35.489
Total: 2H 48Mins 49sec => 168 mins

### Summary
From the above test results, I can be confirmed that the issue has been fixed and the process performance has been improved in the new version.

Thanks for your help, let me notice the missed test case.

**Pull request merged**
