### PR TITLE
broekr   and consumer  Configuration Redelivery Policy conflict

### PR DESCRIPTION
**Pull request by xiangyang-gao**
The operation is as follows：
1.broekr  activemq.xml  add

` <plugins>
            <redeliveryPlugin fallbackToDeadLetter="true" 
                              sendToDlqIfMaxRetriesExceeded="true">
                <redeliveryPolicyMap>
                    <redeliveryPolicyMap>
                        <redeliveryPolicyEntries>
                        <defaultEntry>
                            
                            <redeliveryPolicy maximumRedeliveries="6" 
                                              initialRedeliveryDelay="1000"
                                              redeliveryDelay="1000"/>
                        </defaultEntry>
                    </redeliveryPolicyMap>
                </redeliveryPolicyMap>
            </redeliveryPlugin>
        </plugins>
`
2. Consumer clinet set
     protected int maximumRedeliveries = 6;
    protected long maximumRedeliveryDelay = -1L;
    protected long initialRedeliveryDelay = 1000L;
    protected boolean useCollisionAvoidance;
    protected boolean useExponentialBackOff;
    protected double backOffMultiplier = 5.0D;
    protected long redeliveryDelay;

3.code demo

@Override
    public void execute(PreferencesMessage message) {
        log.info("**********message={}",message);
        throw  new RuntimeException("fail");
    }
4.Problem Description
    log.info("**********message={}",message);
     Log output times：28
     Expected  times： 7

### CODE REVIEW

**Comment by clebertsuconic** [comment]
You should rebase. your branch correctly. if this is to be merged it would create a mess with a big/ huge merge commit.

**Comment by jbonofre** [comment]
Can you please rebase ?

**Comment by jbonofre** [comment]
Can you please rebase and fix the conflicts ?

**Comment by jbonofre** [comment]
Can you please rebase ?

**Comment by clebertsuconic** [comment]
it seems to me that you sent the PR to a wrong branch.

Please do the PR again.. I would start over by branching the right branch.. and then cherry-picking the commit you intended to send.

**Pull request closed without merging**
