### PR TITLE
Fix class loading issues for SSL/nonSSL connectors

### PR DESCRIPTION
**Pull request by cjnygard**
- This resolves issues loading SSL and nonSSL RAR connectors in Glassfish 3.x
- proposed fix for AMQ-5873

### CODE REVIEW

**Comment by cjnygard** [comment]
Not sure if this is the correct way to solve the problem.  The patch incorporates what we've done internally to resolve the issue, which has existed since at least 5.8.x.  We mentioned this issue to Johan at one point. 

Let me know if the proper way to fix this is to derive our own StandaloneObjectFactory-variant and install via the FactoryFinder.setObjectFactory().  It seems as though the thread-local class loader is succeeding but causing cast exception in downstream code instead of failing and dropping through to the normal class loader.  

See Jira issue AMQ-5873 (https://issues.apache.org/jira/browse/AMQ-5873) for stack trace as was reported internally.

**Comment by davsclaus** [comment]
Oh classloading is not fun, if this is merged then it may break something on other systems.

**Comment by mattrpav** [comment]
Agree with Claus, this shouldn't be merged without a better understanding of the root cause. I'm not following how this would fix the problem. Perhaps in Glassfish an undesirable class is being loaded first via the TCCL? Or perhaps a service locator issue.

The current code falls back to the class's classloader if the TCCL does not find the class.

**Comment by lucastetreault** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
