### PR TITLE
AMQ-6452: Upgrade dependency of geronimo-transaction

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by davsclaus** [comment]
Have you done a test / full test with this dependency upgrade as its a major version upgrade?

**Comment by graben** [comment]
Not yet. Good point.

**Comment by graben** [comment]
All tests of dependent modules are green. It's mostly used for unit tests as tx-manager. Implemented JTA API is same for 2.0 and 3.0 versions.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
