### PR TITLE
Remove unused activemq-leveldb test dependencies

### PR DESCRIPTION
**Pull request by coheigea**
Removing some old Tomcat dependencies. No JIRA created as it's just a change to test dependencies.

### CODE REVIEW

**Comment by jbonofre** [comment]
As reminde, leveldb will be completely removed.

**Comment by coheigea** [comment]
Not for 5.16 though?

**Comment by jbonofre** [comment]
That's my intention, I will send an update on the mailing list.

**Comment by coheigea** [comment]
OK fine with me. Could it be applied to 5.15.x then?

**Comment by jbonofre** [comment]
Yes definitely.

**Comment by jbonofre** [comment]
Waiting Jenkins end before merging.

**Pull request merged**
