### PR TITLE
AMQ-8613 Improve performance of selectors with a big sequence of OR and AND logical expressions

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by jbonofre** [comment]
@eolivelli can you please squash all commits in one ? Thanks !

**Comment by eolivelli** [comment]
@jbonofre I have a followup patch, regarding Equals and Not expressions.

I will do have numbers within the end of the week.

**Comment by eolivelli** [comment]
@jbonofre I have a couple of additional enhancements.
I have some numbers on our applications (with this PR + the follow up patches, all stacked), we are saving some good amount of CPU cycles and we decided to commit these changes in our repo.
@dave2wave has some numbers, but I am not sure they are meaningful here.

**Comment by jbonofre** [comment]
Great ! I will do a new pass. Thanks !

**Review by jbonofre — APPROVED** [review]

**Comment by eolivelli** [comment]
@jbonofre thank you for merging this patch.
I will follow up with a second part.

**Pull request merged**
