### PR TITLE
[AMQ-8033] Remove activemq-camel

### PR DESCRIPTION
**Pull request by mattrpav**
- Prerequisite for JMS v2.0 support
 - Prerequisite for Camel 3.x support

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
This is a large feature removal (break for existing use base) has this been voted on?

**Comment by michaelandrepearce** [comment]
I would have thought rather than removal upgrade should have been a less aggressive change. Im fairly certain camel is jms 2 compatible in latest versions.

**Review by mattrpav — COMMENTED** [review]
> This is a large feature removal (break for existing use base) has this been voted on?

@michaelandrepearce The ticket was created ~1 yr ago [AMQ-8033](https://issues.apache.org/jira/browse/AMQ-8033) and makes sense overall to make part of a 5.17.x release stream. Specifically, Camel 3.x ported and took over the component as-is for 3.x and coordinated it as org.apache.camel/camel-activemq [camel-activemq](https://camel.apache.org/components/3.7.x/activemq-component.html)

Release stream alignment with Camel
5.16.x stays with Camel 2.x
5.17.x would have targeted Camel 3.x

**Comment by michaelandrepearce** [comment]
My comment was in regards to removal of out the box camel in the broker. The ticket original was about just upgrade not removal for it to be supported out the box. 

I am aware of user bases dependent on it being there, out the box.

Also just because a ticket is raised doesnt mean its been voted on.

**Comment by mattrpav** [comment]
> My comment was in regards to removal of out the box camel in the broker. The ticket original was about just upgrade not removal for it to be supported out the box.

What do you mean by 'out the box camel in the broker' removal? Camel jars are present in the assembly, as is the camel.xml sample-- which has been converted to use camel-jms in this PR.

> I am aware of user bases dependent on it being there, out the box.

Yep, same here. Users will have plenty of time to adapt given 5.16.x maintaining the as-is Camel 2.x support, and 5.17.x will contain the change. Same as JDK or JEE jar changes. Users can decided when to pull in updated versions of frameworks.

This change also opens up the ability for ActiveMQ to ship Camel 3.x in the future-- which many of those same users will start demanding as Camel 2.x ages out.

> Also just because a ticket is raised doesnt mean its been voted on.

@jbonofre mailed activemq-dev ~3 mos ago.  See message subject: "[PROPOSAL] Remove activemq-camel from Apache ActiveMQ"

**Comment by mattrpav** [comment]
@michaelandrepearce good?

**Comment by michaelpearce-gain** [comment]
> Bonus though! This change also opes up the ability for ActiveMQ to ship Camel 3.x in the future-- which many of those same users will start demanding as Camel 2.x ages out.

This is confusing me somewhat, let me explain some of my understanding and maybe you can correct me where wrong.
1) Today we ship ActiveMQ with Camel 2.x NOT 3.x
2) Out the box based on 1) users are able to have camel routes deployed within ActiveMQ process
3) The code in this PR is needed for Camel 2.x
3) You're removing Camel 2.x support BUT does not add Camel 3.x

Based on this we are essentially removing camel from within the broker.

**Comment by mattrpav** [comment]
> This is confusing me somewhat, let me explain some of my understanding and maybe you can correct me where wrong.
> 
>     1. Today we ship ActiveMQ with Camel 2.x NOT 3.x

Correct

>     2. Out the box based on 1) users are able to have camel routes deployed within ActiveMQ process

Correct

>     3. The code in this PR is needed for Camel 2.x

Incorrect. This PR removes the 'activemq-camel' Camel Component *only*. We still ship Camel 2.x, and this PR update the samples to use o.a.camel.component.jms.JmsComponent instead of o.a.activemq.camel.component.ActiveMQComponent.

see: [Component change](https://github.com/apache/activemq/pull/701/files#diff-1f1cf78427185d2d7a6eb9e106b9e73cbb786ea1d1eb849d3545af2e8497b438L53)

Note: ActiveMQComponent extends from JmsComponent
 
>     4. You're removing Camel 2.x support BUT does not add Camel 3.x

Incorrect. This PR removes just the 'activemq-camel' component, which has been repackaged by Camel as 'camel-activemq' for 3.x

Note: This change is a pre-req for Camel 3.x support as well.

**Comment by michaelpearce-gain** [comment]
Ok thanks, thanks for clarification.

**Review by michaelpearce-gain — APPROVED** [review]

**Pull request merged**
