### PR TITLE
Use UTF-8 instead ISO-8859-1 in activemq-web-console/src/main/webapp/xml/*

### PR DESCRIPTION
**Pull request by SGmuwa**

### CODE REVIEW

**Comment by lucastetreault** [comment]
What is the purpose of this change? Is there an associated JIRA?

**Comment by jbonofre** [comment]
I agree with @lucastetreault. Can you provide some context and purpose ? I don't see strong arguments to change encoding there.

**Comment by SGmuwa** [comment]
@lucastetreault @jbonofre My instance ActiveMQ has non-ISO-8859-1 queue names.

ISO-8859-1:
```xml
<queues>
    <queue name="?? ? ??">
        <stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0" />
        <feed>
            <atom>queueBrowse/?? ? ???view=rss&amp;feedType=atom_1.0</atom>
            <rss>queueBrowse/?? ? ???view=rss&amp;feedType=rss_2.0</rss>
        </feed>
    </queue>
    <queue name="??????, ???!">
        <stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0" />
        <feed>
            <atom>queueBrowse/??????, ???!?view=rss&amp;feedType=atom_1.0</atom>
            <rss>queueBrowse/??????, ???!?view=rss&amp;feedType=rss_2.0</rss>
        </feed>
    </queue>
</queues>
```

UTF-8:
```xml
<queues>
    <queue name="🐶 → 🐈">
        <stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0" />
        <feed>
            <atom>queueBrowse/🐶 → 🐈?view=rss&amp;feedType=atom_1.0</atom>
            <rss>queueBrowse/🐶 → 🐈?view=rss&amp;feedType=rss_2.0</rss>
        </feed>
    </queue>
    <queue name="Привет, Мир!">
        <stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0" />
        <feed>
            <atom>queueBrowse/Привет, Мир!?view=rss&amp;feedType=atom_1.0</atom>
            <rss>queueBrowse/Привет, Мир!?view=rss&amp;feedType=rss_2.0</rss>
        </feed>
    </queue>
</queues>
```

**Comment by lucastetreault** [comment]
I tested on a 5.16.3 broker on Amazon MQ: 
image

And a vanilla 5.17.0 broker on my laptop to be sure: 
image

There doesn't seem to be any problems with the two examples you provided.

**Comment by SGmuwa** [comment]
@lucastetreault Click in «Queue Views» button «XML»

**Comment by lucastetreault** [comment]
Ah thanks for the clarification. I see the issue now: 
image

**Comment by SGmuwa** [comment]
You can also hot-replace files while ActiveMQ is running and the issue will be gone.

```bash
sed -i s/ISO-8859-1/UTF-8/g /opt/activemq/webapps/admin/xml/*.jsp
```

Where `/opt/activemq/` — path to ActiveMQ app.

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
