### PR TITLE
AMQ-7455 Mitigate high connection bootstrap/teardown frequency...

### PR DESCRIPTION
**Pull request by chammp**
...when running in a EAP6 XA transactional environment.
More information can be found in https://issues.apache.org/jira/browse/AMQ-7455

### CODE REVIEW

**Comment by jbonofre** [comment]
I guess it's fixed with AMQ-5790, right ?

**Comment by jbonofre** [comment]
Any update about my comment related to AMQ-5790 ?

**Comment by chammp** [comment]
> Any update about my comment related to AMQ-5790 ?

Ah, sorry for not answering at all.
As a matter of fact we did not yet check the fix because we were successfully using a patched version built in-house and we did not migrate to a newer version of the RA. But we did migrate to EAP7 in the meantime, so the whole setup changed. As far as I know with the current setup and the current EAP7 resource adapter the behavior we witnessed in March don't occur anymore.

**Comment by lucastetreault** [comment]
Can one of the admins verify this patch?

**Comment by jbonofre** [comment]
@chammp thanks for the update. I think that AMQ-5790 already fix the issue, but I have to double check.

**Pull request closed without merging**
