### PR TITLE
[AMQ-8976] Add maxConnectionExceededCount metric for connectors

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by mattrpav** [comment]
This is pretty straight-forward. Leaving this open for 72-hours for any review, then plan to merge.

**Comment by mattrpav** [comment]
@cshannon added support for resetStatistics()

**Comment by cshannon** [comment]
@mattrpav - I think github has an option to submit a PR for draft review.

This way people know you are still making changes because otherwise you will add people like myself and request a review and I have no clue if you are finished.

**Comment by cshannon** [comment]
It doesn't make sense to ask people to review a PR if you are pushing new commits every 5 minutes and still working on it: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by mattrpav** [comment]
@cshannon sounds good, I will be sure to use draft PR's in the future. 

FWIW- in this instance, I was doing my last once over when I noticed the mbean had a 'resetStatistics' method and I didn't want to push in an incomplete feature.

**Comment by cshannon** [comment]
> @cshannon sounds good, I will be sure to use draft PR's in the future.
> 
> FWIW- in this instance, I was doing my last once over when I noticed the mbean had a 'resetStatistics' method and I didn't want to push in an incomplete feature.

Maybe in this last commit but you've been pushed several commits since asking for a review and in general your usual workflow has been to submit a PR when it's not ready and add people for review and we all end up just getting a bunch of emails every time you force push a commit. The end result is I just treat it like spam and ignore it as I assume you are not done.

With the draft PR at least we know it's a preview so we can take a look and check it out early to make comments if we want and then know you are finished if you mark it as a normal PR and not draft.

**Comment by mattrpav** [comment]
> Maybe in this last commit but you've been pushed several commits since asking for a review and in general your usual workflow has been to submit a PR when it's not ready and add people for review and we all end up just getting a bunch of emails every time you force push a commit. The end result is I just treat it like spam and ignore it as I assume you are not done.
> 
> With the draft PR at least we know it's a preview so we can take a look and check it out early to make comments if we want and then know you are finished if you mark it as a normal PR and not draft.

Lol... yeah, sorry. I'll be sure to use Draft PR's and tidy up the workflow going forward =)

**Comment by cshannon** [comment]
Yeah no problem I didn't realize draft PRs were a thing until recently so I figured I mention it as I assume you didn't know about it either. Seems like the perfect thing to use for stuff (especially big commits like the JMS 2.0 stuff)

**Pull request merged**
