### PR TITLE
AMQ-8275 - Java 16 SSL - reflection warning

### PR DESCRIPTION
**Pull request by jgallimore**
This PR avoids the need to use reflection to explicitly set the hostname on the socket, instead providing the hostname via a SSLParameter. I have tested this using a HAProxy proxy server to route requests from a client to a broker based on the host name.

### CODE REVIEW

**Comment by pax95** [comment]
Is there any news any news on this issue since it blocks for update to java 17 ?

**Comment by jbonofre** [comment]
FYI, I'm working on it. I'm fixing assembly build and then I will rebase/merge this PR.

**Review by jbonofre — APPROVED** [review]

**Comment by pax95** [comment]
@jgallimore @jbonofre Great job taking care of this. Thanks and merry christmas !!

**Comment by iPet** [comment]
@jbonofre Any ideas on when we can expect a new release including this fix?

**Comment by jbonofre** [comment]
@iPet 5.16.4 vote will start soon (hopefully during the week end or early next week).

**Comment by fabiojuniork13** [comment]
@jbonofre, hello!
I have the same problem, but I am using the openjdk 18. The lasted version of openjdk.
Do you know how to solve this problem, please? I think this is because I am using the openjdk, because in another environment with oracle jdk this problem not happen.

**Pull request merged**
