### PR TITLE
AMQ-6057: Add performance patch to JDBC statements definition

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by davsclaus** [comment]
@gtully @tabish121 this seems fine to me, but want to double check by some of the AMQ guys whom knows the JDBC datastore better than me.

**Comment by graben** [comment]
The patch is almost one year old. Running fine for almost the same amount of time.

**Comment by davsclaus** [comment]
Have you run with a patched version in production for a year? What JDBC database are you using?

And the SQL syntax changes are standard SQL which is supported on all major databases?

**Comment by graben** [comment]
> Have you run with a patched version in production for a year?

Yes

> What JDBC database are you using?

Oracle

>And the SQL syntax changes are standard SQL which is supported on all major databases?

Yes

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
