### PR TITLE
Provide RMI registry implementation to prevent re-bind

### PR DESCRIPTION
**Pull request by jgallimore**

### CODE REVIEW

**Comment by coheigea** [comment]
There are some test failures in activemq-karaf-itest due to the sun.rmi dependency that's added:

org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=activemq; type=karaf.feature; version="[5.16.0.SNAPSHOT,5.16.0.SNAPSHOT]"; filter:="(&(osgi.identity=activemq)(type=karaf.feature)(version>=5.16.0.SNAPSHOT)(version<=5.16.0.SNAPSHOT))" [caused by: Unable to resolve activemq/5.16.0.SNAPSHOT: missing requirement [activemq/5.16.0.SNAPSHOT] osgi.identity; osgi.identity=activemq-karaf; type=osgi.bundle; version="[5.16.0.SNAPSHOT,5.16.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve activemq-karaf/5.16.0.SNAPSHOT: missing requirement [activemq-karaf/5.16.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.apache.activemq.console.command)" [caused by: Unable to resolve org.apache.activemq.activemq-osgi/5.16.0.SNAPSHOT: missing requirement [org.apache.activemq.activemq-osgi/5.16.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=sun.rmi.registry)"]]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)

**Comment by jbonofre** [comment]
`sun.rmi.registry` package should be set as optional. Especially, the rebinding is not a problem on Karaf. I'm testing the change, and I will provide the patch diff to @jgallimore

**Comment by jgallimore** [comment]
Thanks for the feedback @jbonofre @coheigea - I'll try and get that addressed this afternoon.

**Comment by jgallimore** [comment]
I'm not sure I get the same test failures. I get this:

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.activemq.karaf.itest.ActiveMQBrokerRuntimeConfigTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 227.394 s <<< FAILURE! - in org.apache.activemq.karaf.itest.ActiveMQBrokerRuntimeConfigTest
[ERROR] org.apache.activemq.karaf.itest.ActiveMQBrokerRuntimeConfigTest  Time elapsed: 227.393 s  <<< ERROR!
java.lang.RuntimeException: Cannot get the remote bundle context
Caused by: java.rmi.ConnectException: 
Connection refused to host: 192.168.37.13; nested exception is: 
	java.net.ConnectException: Operation timed out (Connection timed out)
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)

[ERROR] org.apache.activemq.karaf.itest.ActiveMQBrokerRuntimeConfigTest  Time elapsed: 227.393 s  <<< ERROR!
java.lang.RuntimeException: Container never came up
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ActiveMQAMQPBrokerFeatureTest.org.apache.activemq.karaf.itest.ActiveMQAMQPBrokerFeatureTest » Runtime
[ERROR]   ActiveMQBrokerBlueprintTest.org.apache.activemq.karaf.itest.ActiveMQBrokerBlueprintTest » Runtime
[ERROR]   ActiveMQBrokerFeatureTest.org.apache.activemq.karaf.itest.ActiveMQBrokerFeatureTest » Runtime
[ERROR]   ActiveMQBrokerNdCamelFeatureTest.org.apache.activemq.karaf.itest.ActiveMQBrokerNdCamelFeatureTest » Runtime
[ERROR]   ActiveMQBrokerNdExternalCamelFeatureTest.org.apache.activemq.karaf.itest.ActiveMQBrokerNdExternalCamelFeatureTest » Runtime
[ERROR]   ActiveMQBrokerRuntimeConfigTest.org.apache.activemq.karaf.itest.ActiveMQBrokerRuntimeConfigTest » Runtime
[ERROR]   ActiveMQClientBundleTest.org.apache.activemq.karaf.itest.ActiveMQClientBundleTest » Runtime
[ERROR]   ActiveMQClientFactoryTest.org.apache.activemq.karaf.itest.ActiveMQClientFactoryTest » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » Runtime
[INFO] 
[ERROR] Tests run: 16, Failures: 0, Errors: 16, Skipped: 0


Any pointers you can give me?

**Comment by jbonofre** [comment]
No, that's different IMHO. Let me run a new build to see if I have the same. We have to check in the pax-exam container `karaf.log` to see why the container doesn't start.

**Comment by jgallimore** [comment]
I don't appear to get that log at all here. I'll retry against master.

**Comment by jgallimore** [comment]
I seem to get the same thing with master. I'll try another computer.

**Pull request closed without merging**
