### PR TITLE
Update Spring to 5.3.18.

### PR DESCRIPTION
**Pull request by jgallimore**
This PR updates the Spring Framework version used in ActiveMQ to 5.3.18.

### CODE REVIEW

**Comment by jgallimore** [comment]
I'm not sure what's up with the CI as this built ok locally before I submitted the PR. I'll take a look and see if I can reproduce.

**Comment by jbonofre** [comment]
@jgallimore let me take a look as well. Thanks for the PR anyway.

**Comment by jbonofre** [comment]
@jgallimore it seems to be related to Jetty (web module). Let me fix that (probably on a different PR). I will let you know when ready to rebase.

**Comment by jgallimore** [comment]
Thanks @jbonofre!

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
