### PR TITLE
[AMQ-8409]  Unexpected \\r instead of \r in header property in incoming messages when using STOMP 1.2 

### PR DESCRIPTION
**Pull request by fscrec**

### CODE REVIEW

**Review by mattrpav — CHANGES_REQUESTED** [review]
Would you add a negative test to STOMP 1.0 and 1.1 version tests?

**Comment by mattrpav** [comment]
FYI-- I kicked off new test run on Jenkins

**Comment by mattrpav** [comment]
@fscrec thanks!

**Review by mattrpav — CHANGES_REQUESTED** [review]
@fscrec the code fixes look great. One minor administrative change-- can you make the PR against 'main', so we can cherry pick it to other branches? I think this will allow it to get the unit tests to pass.

**Comment by fscrec** [comment]
@mattrpav I've created a new pull request #736 for the main branch containing only three commits contained here (but from the main branch as the origin as opposed to 5.16.x I used in this PR). Should this PR be closed?

**Comment by jbonofre** [comment]
For the record, you can squash the commits in one and focus only on `main` branch (then we cherry pick on other branches).

**Comment by mattrpav** [comment]
@fscrec yep, I'll close this one. Thanks for the PR!

**Pull request closed without merging**
