### PR TITLE
AMQ-8530 - Update to geronimo-annotation_1.3_spec

### PR DESCRIPTION
**Pull request by cshannon**

### CODE REVIEW

**Comment by cshannon** [comment]
This fixes MessageDestinationVirtualTopicTest as well as any other tests that might use @Resource for autowiring

**Comment by cshannon** [comment]
> @cshannon can you add an update to the features-core in activemq-karaf?

Yep I'll fix it, I only searched pom.xml for references but should have searched all files for the reference

**Review by mattrpav — APPROVED** [review]
LGTM

**Comment by cshannon** [comment]
Rebased and pushed again to re-run tests as CI seemed to crash.

**Pull request merged**
