### PR TITLE
Unit tests for AMQ-8053

### PR DESCRIPTION
**Pull request by lucastetreault**
Add some unit tests for https://issues.apache.org/jira/browse/AMQ-8053.

### CODE REVIEW

**Comment by jbonofre** [comment]
Are you sure about this test ? At first glance, it doesn't seem fully correct to me.

**Comment by lucastetreault** [comment]
Any specific concerns? The first two demonstrate the existing functionality and the 3rd shows the change to not override it when the message goes through a network of brokers. Seems correct to me 🙂

**Comment by mattrpav** [comment]
@lucastetreault appreciate the PR work here =). However, given it is my change, I need to do the tests. 

New PR  [758](https://github.com/apache/activemq/pull/758) re-uses network connector test framework and puts the unit tests in activemq-unit-tests instead of activemq-broker.

**Comment by lucastetreault** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
