### PR TITLE
[AMQ-9111] Upgrade to Jackson 2.13.4

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by jbonofre** [comment]
Didn't you see my comment ? I think it's better to directly upgrade to 2.14.0.rc1.

**Comment by gemmellr** [comment]
RC2 is already out, though the maintainer doesnt recommend using either in production and 2.14.0 isnt due for 3-4 weeks.

2.13.4.1 also seems likely to be coming with a backport of the newest issue.

**Comment by jbonofre** [comment]
My point is that current 2.13.x version doesn't fix latest issues/security issues. So for me it doesn't make sense to upgrade, better to wait 2.14 or 2.13 including latest security fixes.

**Comment by gemmellr** [comment]
Not sure it makes a big difference, fixes 1 of the 2 so its better than not doing anything, and can always do another upgrade when a suitable release is actually available. Seems as useful as updating to a candidate the maintainer pleads that you shouldn't ever use for a final release.

**Comment by jbonofre** [comment]
@gemmellr it sounds reasonable. Agree.

**Comment by gemmellr** [comment]
databind 2.13.4.2 was released with backport of the other issue fix.

**Pull request closed without merging**
